/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flush.dry.cleaning.service;

import java.awt.GridLayout;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
/**
 *
 * @author Kimaiga
 */
public class CustomerLogin extends javax.swing.JFrame {
    //declare database variables    
        Connection conn= null;
        String url = "jdbc:mysql://localhost/";
        String dbName = "flush_drycleaners";
        String driver ="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        Statement st;
        ResultSet rs;

    JLabel ul,pl,npl,cpl;
    JTextField ut;
    JPasswordField up,np,cp;        


    /**
     * Creates new form Admin_login
     */
    public CustomerLogin() {
               /** Creates new form user account */
   
        //try catch prevent the program from crashing
	    	 try{
	       Class.forName(driver);//DriverManager:
//It is a class of java.sql package that controls a set of JDBC drivers. Each driver has to be register with this class.

             conn =  DriverManager.getConnection(url+dbName,userName,password);//getConnection(String url, String userName, String password):
//This method establishes a connection to specified database url. It takes three string types of arguments like:

              st = conn.createStatement();//con.close():
//This method is used for disconnecting the Ams2. It frees all the resources occupied by the database

             System.out.println("connection to database has been established");

	            }
  catch(Exception exp){
	              JOptionPane.showMessageDialog(null, "Connection to the database has not been established successsfully." + exp.getMessage());
	            }
        initComponents();
        setLocationRelativeTo(null);
        this.setResizable(false);
//        ps=new PasswordService();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN AS CLIENT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flush/dry/cleaning/service/clear_left.png"))); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("RESET YOUR PASSWORD");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Exit System");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtpass, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                .addComponent(txtuser)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(380, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int a=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to exit?", "EXIT", JOptionPane.YES_NO_OPTION);
        if (a==JOptionPane.OK_OPTION) {
            System.exit(0);
            
            
        } else {
//            this.show(true);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String userInput=txtuser.getText();
        String userInput2=txtpass.getText();
    //field validation    
        if("".equals(userInput) ||"".equals(userInput2)){
        
            JOptionPane.showMessageDialog(rootPane, "Please enter your username and password.","ERROR",JOptionPane.ERROR_MESSAGE);
        }

  //  if (cbodomain.getSelectedItem().toString().equals("Administrator"))
        try {
           // String passenc=ps.encrypt(userInput2);
                 String sql="SELECT * FROM customer_details WHERE username='"+userInput+"'and password ='"+userInput2+"'";
                 st.execute(sql);
                  rs=st.executeQuery(sql);
                /*  int c=0;
                  while(rs.next())
                  {
                    c++;
                    String domain=rs.getString("domain");
                  } */    
                //Code to specify domain parameters    
     //      if (cbodomain.getSelectedItem().toString().equals("Customer"))
                  
                   JOptionPane.showMessageDialog(rootPane, "You are logging in as Client....");
                      CustomerNavigation Tv=new CustomerNavigation ();
                      Tv.setVisible(true);
                      this.setVisible(false);                    
                  
    
               /*   else if(c==1 && "Station Officer".equals(level)){
                    JOptionPane.showMessageDialog(rootPane, "You are logging in as Returning Officer....");
                    new StationOfficer().show();
                    this.dispose();
                }*/

                  
                  
            } catch (Exception f) {
                JOptionPane.showMessageDialog(rootPane, f.getMessage());
            }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       txtuser.setText("");
        txtpass.setText("");
//        cbodomain .setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new SelectAccessLevel().setVisible(true);
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        
 //Create our Jpanel       
        JPanel panel=new JPanel();
        panel.setLayout(new GridLayout(4, 2));
        //the labels
        ul=new JLabel("User name");
        pl=new JLabel("Old Password");
        npl=new JLabel("New Password");
        cpl=new JLabel("Confirm Password");

        //the textfield
        ut=new JTextField();
        ut.setSize(50, 15);

        //the passwordfields
        up=new JPasswordField();
        up.setSize(50, 15);
        np=new JPasswordField();
        np.setSize(50, 15);
        cp=new JPasswordField();
        cp.setSize(50, 15);



        panel.add(ul);
        panel.add(ut);
        panel.add(pl);
        panel.add(up);
        panel.add(npl);
        panel.add(np);
        panel.add(cpl);
        panel.add(cp);
        int a=JOptionPane.showConfirmDialog(null, panel,"RESET PASSWORD",JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
        if(a==JOptionPane.OK_OPTION) {
            String username=ut.getText();
            String userpassword=up.getText();
            String newpassword=np.getText();
            String confirmpassword=cp.getText();
            int newpasswordlength=newpassword.length();
            
            if (username.equals("")||userpassword.equals("")||newpassword.equals("")||confirmpassword.equals("")) {
                JOptionPane.showMessageDialog(panel, "Fill all the entries");
            } else if(!newpassword.equals(confirmpassword)) {
                JOptionPane.showMessageDialog(null, "<html><font color=red>Passwords are not the same</font></html>");
            }else if(newpasswordlength >10 ||newpasswordlength ==10){
                
                ////what happens if password is not null and new and confirm pass are equal
             try {
                //            String passenc=ps.encrypt(userpassword);
//            String userpassencrypted=ps.encrypt(userpassword);
                            
                            try {
                 String sql="SELECT * FROM customer_details WHERE username='"+username+"'and password ='"+userpassword+"'";
                 st.execute(sql);
                  rs=st.executeQuery(sql);

                     try {
                          String sql_update="Update customer_details set password = '"+userpassword+"' where username = '"+username+"'";
                           st =   (Statement) conn.prepareStatement(sql_update);
                            st.executeUpdate(sql_update);
                            JOptionPane.showMessageDialog(null, "Password Changed");
//


                      } catch (Exception e) {
                          JOptionPane.showMessageDialog(null, e.getMessage());
                          
                      }

            } catch (Exception f) {
                JOptionPane.showMessageDialog(rootPane, f.getMessage());
                
            }
                            
            } catch (Exception ex) {
                Logger.getLogger(CustomerLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Password Length should be 8 or more.");
                
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
               
        ////////////////////////////////////
        ///////Give the Gui window /////////
        /////// look and feel      /////////
        ////////////////////////////////////
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
