/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flush.dry.cleaning.service;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.event.ChangeListener;
import java.text.DateFormat;

/**
 * @author Nelson Kimaiga

 */
public class Deposit extends javax.swing.JFrame {
    
      Connection con = null;
    String url = "jdbc:mysql://localhost/";// url: - Database url where stored or created your database
    String dbName = "flush_drycleaners";
    String driver = "com.mysql.jdbc.Driver";
    String userName = "root";//  userName: - User name of MySQL
    String password = "";// password: -Password of MySQL
    Statement st;
    Statement stmt;
    ResultSet rs;
    SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
    private String UI;
    
    public void loadvalues(){
    jeans1.setText("0");
    shirt1.setText("0");
    tshirt1.setText("0");
    sweater1.setText("0");
    jacket1.setText("0");
    coat1.setText("0");
    trouser1.setText("0");
    txtothers.setText("0");
    }
    
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    


    /**
     * Creates new form Clothes_Deposit
     */
    public Deposit() {
        initComponents();
        connect ();
        setLocationRelativeTo(null);
        this.setResizable(false);
        
    loadvalues();
    }
 public void connect(){
          try{
           /*Connection*/ con = DriverManager.getConnection("jdbc:mysql://localhost:3306/flush_drycleaners","root","");
            System.out.println("Connection with Database Established");
            /*Statement stmt = conn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery("select * from login");*/
            stmt = con.createStatement();
         String sql = "SELECT * FROM cloth_deposit";
         rs = stmt.executeQuery(sql);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Connection to the database has not been established successsfully." + e.getMessage());
            System.out.println("Error:"+e);
        }

        
    
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        customeridcd2 = new javax.swing.JTextField();
        numberofclothescd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sub = new javax.swing.JButton();
        CF = new javax.swing.JButton();
        jeans1 = new javax.swing.JTextField();
        shirt1 = new javax.swing.JTextField();
        trouser1 = new javax.swing.JTextField();
        coat1 = new javax.swing.JTextField();
        jacket1 = new javax.swing.JTextField();
        tshirt1 = new javax.swing.JTextField();
        sweater1 = new javax.swing.JTextField();
        Numberofclothes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dobcollection = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtothers = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAUNDRY DEPOSIT");
        setPreferredSize(new java.awt.Dimension(848, 470));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LAUNDRY DEPOSIT");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Customer ID");

        numberofclothescd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofclothescdActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Cloth types");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel5.setText("Jeans");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel6.setText("Shirt(s)");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel7.setText("T-shirt(s)");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("Sweater(s)");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setText("Trouser(s)");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("Coat(s)");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setText("Jacket(s)");

        sub.setText("Submit");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        CF.setText("CLEAR FIELDS");
        CF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFActionPerformed(evt);
            }
        });

        jeans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeans1ActionPerformed(evt);
            }
        });

        Numberofclothes.setText("No of clothes");
        Numberofclothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberofclothesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Date of Deposit");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel12.setText("Customer Details");

        dobcollection.setMaxSelectableDate(new java.util.Date(1451512873000L));
        dobcollection.setMinSelectableDate(new java.util.Date(1427234473000L));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel13.setText("Others");

        jMenu1.setText("File");

        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(customeridcd2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dobcollection, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tshirt1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sweater1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(130, 130, 130)
                                        .addComponent(CF)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sub)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jacket1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Numberofclothes)
                                        .addGap(18, 18, 18)
                                        .addComponent(numberofclothescd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(shirt1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(84, 84, 84)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jeans1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(jLabel10)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coat1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trouser1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 250, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(customeridcd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(dobcollection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jeans1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shirt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(trouser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tshirt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jacket1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sweater1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberofclothescd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numberofclothes)
                    .addComponent(CF)
                    .addComponent(sub))
                .addGap(117, 117, 117))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
     String CustomerID = customeridcd2.getText();
   
  /*   try {
             Integer.parseInt (CustomerID);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Customer_ID", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }*/
        String noc = numberofclothescd.getText();
         try {
             Integer.parseInt (noc);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Number_of_clothes", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
                     
        String j = jeans1.getText();
         try {
             Integer.parseInt (j);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at jeans", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String s = shirt1.getText();
         try {
             Integer.parseInt (s);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at shirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String ts = tshirt1.getText();
         try {
             Integer.parseInt (ts);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at tshirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String st1 = sweater1.getText();
         try {
             Integer.parseInt (st1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at sweater", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String t = trouser1.getText();
         try {
             Integer.parseInt (t);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at trouser", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String c = coat1.getText();
         try {
             Integer.parseInt (c);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at coat", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String jt1 = jacket1.getText();
        try {
             Integer.parseInt (jt1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at jacket", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
 String others = txtothers.getText();
        try {
             Integer.parseInt (others);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at other clothes", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }       
        
        String dat = format.format(dobcollection.getDate());
        

       try{

            String sql = "INSERT INTO cloth_deposit(Customer_ID,Number_of_clothes,Jeans,Shirt,T_shirt,Sweater,Trouser,Coat,Jacket,others,deposit_Date, isDeleted) VALUES('"+CustomerID+"', '"+noc+"', '"+j+"', '"+s+"', '"+ts+"', '"+st1+"', '"+t+"', '"+c+"', '"+jt1+"','"+others+"', '"+dat+"',0)";
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Details succesfully saved!", "Confirmatory Message", JOptionPane.PLAIN_MESSAGE);

            this.customeridcd2.setText("");
            this.numberofclothescd.setText("");
            this.jeans1.setText("");
            this.shirt1.setText("");
            this.tshirt1.setText("");
             this.sweater1.setText("");
            this.trouser1.setText("");
            this.coat1.setText("");
            this.jacket1.setText("");
            txtothers.setText("");
            dobcollection.setDate(null);
            
            

        }catch (SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
            
        }         

        // TODO add your handling code here:
    }//GEN-LAST:event_subActionPerformed

    private void CFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFActionPerformed
Deposit CD = new Deposit();
CD.setVisible(true);
dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_CFActionPerformed

    private void NumberofclothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberofclothesActionPerformed
        int num1;
        int num2;
        int num3;
        int num4;
        int num5;
        int num6;
        int num7;
        int num8;
        
        
        
        try{
        num1=Integer.parseInt(this.jeans1.getText());
        
        num2=Integer.parseInt(this.shirt1.getText());
        num3=Integer.parseInt(this.tshirt1.getText());
        num4=Integer.parseInt(this.sweater1.getText());
        num5=Integer.parseInt(this.jacket1.getText());
        num6=Integer.parseInt(this.coat1.getText());
        num7=Integer.parseInt(this.trouser1.getText());
        num8=Integer.parseInt(this.txtothers.getText());
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "Wrong input value","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
        int number = ((num1) + (num2) + (num3) + (num4) + (num5) + (num6) + (num7) +(num8));
        this.numberofclothescd.setText(""+number);
//Code to validate input fields        
if( number== 0){ 
    System.out.println("Number is equal to zero"); 
}
    else if (number > 0){ 
        System.out.println("Number is positive"); 
    }
 
    else {
 //Code that checks negative values and resets input fields
 JOptionPane.showMessageDialog(this, "Negative input value!","ERROR",JOptionPane.ERROR_MESSAGE);
 this.numberofclothescd.setText("");
             this.customeridcd2.setText("");
            this.numberofclothescd.setText("");
            this.jeans1.setText("");
            this.shirt1.setText("");
            this.tshirt1.setText("");
             this.sweater1.setText("");
            this.trouser1.setText("");
            this.coat1.setText("");
            this.jacket1.setText("");
            txtothers.setText("");
    
   }
      
  // TODO add your handling code here:
        
    }//GEN-LAST:event_NumberofclothesActionPerformed

    private void numberofclothescdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofclothescdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofclothescdActionPerformed

    private void jeans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeans1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new CustomerNavigation().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        ////////////////////////////////////
        ///////Give the Gui window /////////
        /////// look and feel      /////////
        ////////////////////////////////////
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Deposit().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CF;
    private javax.swing.JButton Numberofclothes;
    private javax.swing.JTextField coat1;
    public static javax.swing.JTextField customeridcd2;
    private com.toedter.calendar.JDateChooser dobcollection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jacket1;
    private javax.swing.JTextField jeans1;
    private javax.swing.JTextField numberofclothescd;
    private javax.swing.JTextField shirt1;
    private javax.swing.JButton sub;
    private javax.swing.JTextField sweater1;
    private javax.swing.JTextField trouser1;
    private javax.swing.JTextField tshirt1;
    private javax.swing.JTextField txtothers;
    // End of variables declaration//GEN-END:variables
}
