/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flush.dry.cleaning.service;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.event.ChangeListener;


import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Kimaiga
 */
public class Payment extends javax.swing.JFrame {
        Connection conn= null;
        PasswordEncryption ps;
        String url = "jdbc:mysql://localhost/";
        String dbName = "flush_drycleaners";
        String driver ="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        Statement st;
        ResultSet rs;
    SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
    private String UI;

    private String sql;
    
      public void loadvalues(){
    jeans.setText("0");
    shirt.setText("0");
    tshirt.setText("0");
    sweater.setText("0");
    jacket.setText("0");
    coat.setText("0");
    trouser.setText("0");
    others.setText("0");
    }
    
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
   /**
     * Creates new form StoreCalculator
     */
    public Payment() {

        initComponents();
         setLocationRelativeTo(null);
        this.setResizable(false);
    loadvalues();
    
    try{
	       Class.forName(driver);

             conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url+dbName,userName,password);

              st = (com.mysql.jdbc.Statement) conn.createStatement();

            // this.setTitle("Users Account");

	      }


	            catch(Exception exp)
                    {
	              JOptionPane.showMessageDialog(null, "Cannot connect to the database, check network settings.","ERROR",JOptionPane.ERROR_MESSAGE);
	            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CN = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jeans = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        shirt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tshirt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        sweater = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jacket = new javax.swing.JTextField();
        coat = new javax.swing.JTextField();
        trouser = new javax.swing.JTextField();
        getcost = new javax.swing.JButton();
        CALCsub = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        totalcost = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        CF = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        amountpaid = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        GETBALANCE = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        jeansp = new javax.swing.JTextField();
        shirtp = new javax.swing.JTextField();
        tshirtp = new javax.swing.JTextField();
        sweaterp = new javax.swing.JTextField();
        jacketp = new javax.swing.JTextField();
        coatp = new javax.swing.JTextField();
        trouserp = new javax.swing.JTextField();
        display = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cboplan = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtothers = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        others = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbomode = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSACTION CALCULATION");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("COST CALCULATOR-Click on Display Price button ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Jeans");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Shirt");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("T-shirt");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Sweater");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Jacket");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Coat");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Trouser");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Prices");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("Customer ID");

        CN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("Jeans");

        jeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeansActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("Shirt");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("T-shirt");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("Sweater");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("Trouser");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setText("Coat");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel24.setText("Jacket");

        getcost.setText("GET COST");
        getcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getcostActionPerformed(evt);
            }
        });

        CALCsub.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        CALCsub.setText("SUBMIT TRANSACTION");
        CALCsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CALCsubActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel25.setText("Total Cost");

        totalcost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalcostActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel26.setText("The fields below will fill up after putting your customer ID");

        CF.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        CF.setText("CLEAR FIELDS");
        CF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CFActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel27.setText("Amount paid");

        amountpaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountpaidActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setText("Balance");

        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        GETBALANCE.setText("GET BALANCE");
        GETBALANCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETBALANCEActionPerformed(evt);
            }
        });

        Report.setText("Reciept");
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        jeansp.setEditable(false);

        shirtp.setEditable(false);

        tshirtp.setEditable(false);

        sweaterp.setEditable(false);
        sweaterp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sweaterpActionPerformed(evt);
            }
        });

        jacketp.setEditable(false);

        coatp.setEditable(false);

        trouserp.setEditable(false);

        display.setText("Display prices");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Plan");

        cboplan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cboplan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal price" }));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Insert your Customer ID");

        jButton1.setText("Number of clothes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Others");

        txtothers.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel13.setText("Others");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Payment Mode");

        cbomode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT A MODE--", "Cash" }));

        jMenu1.setText("File");

        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(amountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(GETBALANCE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel28)
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(shirtp, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel4))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(tshirtp, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                                    .addComponent(jeansp))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addGap(9, 9, 9)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coatp)
                                    .addComponent(jacketp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sweaterp, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CALCsub)
                                .addGap(35, 35, 35)
                                .addComponent(CF))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sweater))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(tshirt, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(jLabel19)
                                                    .addGap(30, 30, 30))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel18)
                                                    .addGap(28, 28, 28)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(shirt, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jeans, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel13))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(others)
                                    .addComponent(jacket, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                    .addComponent(coat)
                                    .addComponent(trouser))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(getcost)
                                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(totalcost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(94, 94, 94))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(trouserp, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                                    .addComponent(cboplan, 0, 114, Short.MAX_VALUE)
                                                    .addComponent(txtothers))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(display))
                                            .addComponent(Report, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap())))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(74, 74, 74)
                                        .addComponent(jLabel14)
                                        .addGap(53, 53, 53))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(cbomode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(94, 94, 94))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jeansp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sweaterp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trouserp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(shirtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jacketp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tshirtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(coatp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cboplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(display))))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cbomode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(coat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(shirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(tshirt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(trouser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(sweater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(others, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jacket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(getcost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalcost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(amountpaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GETBALANCE)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CALCsub)
                    .addComponent(CF)
                    .addComponent(Report))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalcostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalcostActionPerformed

    private void getcostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getcostActionPerformed
        int num1;
        int num2;
        int num3;
        int num4;
        int num5;
        int num6;
        int num7;
        int num8;
        int num9;
        int num10;
        int num11;
        int num12;
        int num13;
        int num14;
        int num15;
        int num16;
        
        
        try{
       num1=Integer.parseInt(this.jeans.getText());
       num2=Integer.parseInt(this.shirt.getText());
        num3=Integer.parseInt(this.tshirt.getText());
        num4=Integer.parseInt(this.sweater.getText());
       num5=Integer.parseInt(this.jacket.getText());
       num6=Integer.parseInt(this.coat.getText());
       num7=Integer.parseInt(this.trouser.getText());
       num16=Integer.parseInt(this.others.getText());
         num8=Integer.parseInt(this.jeansp.getText());
       num9=Integer.parseInt(this.shirtp.getText());
        num10=Integer.parseInt(this.tshirtp.getText());
        num11=Integer.parseInt(this.sweaterp.getText());
       num12=Integer.parseInt(this.jacketp.getText());
       num13=Integer.parseInt(this.coatp.getText());
       num14=Integer.parseInt(this.trouserp.getText());
       num15=Integer.parseInt(this.txtothers.getText());
        }
        
        catch(Exception e){
       JOptionPane.showMessageDialog(this, "No values to be computed!","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
        int cost = ((num1*num8) + (num2*num9) + (num3*num10) + (num4*num11) + (num5*num12) + (num6*num13) + (num7*num14) + (num16*num15));
        this.totalcost.setText(""+cost);
        // TODO add your handling code here:
    }//GEN-LAST:event_getcostActionPerformed


    private void CALCsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CALCsubActionPerformed
 String CustomerID =CN.getText();

        String js = jeans.getText();
         try {
             Integer.parseInt (js);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Jeans", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String srt= shirt.getText();
         try {
             Integer.parseInt (srt);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at shirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String tt= tshirt.getText();
         try {
             Integer.parseInt (tt);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Tshirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String sw= sweater.getText();
         try {
             Integer.parseInt (sw);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Sweater", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String jt = jacket.getText();
         try {
             Integer.parseInt (jt);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Jacket", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String ct = coat.getText();
         try {
             Integer.parseInt (ct);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Coat", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String tr = trouser.getText();
         try {
             Integer.parseInt (tr);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at Trouser", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
         
          String otherclothes = others.getText();
         try {
             Integer.parseInt (otherclothes);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at other clothes", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
  
         }       
         
        
        String tc = totalcost.getText();
        String am = amountpaid.getText();
         try {
             Integer.parseInt (am);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "INPUT FIELDS ARE EMPTY!", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
        String be  = balance.getText();
        

        try{

            String sql = "INSERT INTO payments(Customer_ID,Jeans,shirt,T_shirt,sweater,jacket,coat,trouser,others, totalcost,Amountpaid,Balance) VALUES('"+CustomerID+"', '"+js+"', '"+srt+"', '"+tt+"','"+sw+"', '"+jt+"', '"+ct+"', '"+tr+"', '"+otherclothes+"', '"+tc+"','"+am+"', '"+be+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Details succesfully saved!", "Confirmatory Message", JOptionPane.PLAIN_MESSAGE);

   Collection.cid.setText(this.CN.getText());

        
            this.CN.setText("");
            this.jeans.setText("");
            this.shirt.setText("");
            this.tshirt.setText("");
            this.sweater.setText("");
             this.jacket.setText("");
            this.coat.setText("");
            this.trouser.setText("");
            this.totalcost.setText("");
            this.amountpaid.setText ("");
            this.balance.setText("");
            txtothers.setText("");
            search.setText("");
            
  
        
        // TODO add your handling code here:
     
        }catch (SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CALCsubActionPerformed

    private void CFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CFActionPerformed
          this.CN.setText("");
            this.jeans.setText("");
            this.shirt.setText("");
            this.tshirt.setText("");
            this.sweater.setText("");
             this.jacket.setText("");
            this.coat.setText("");
            this.trouser.setText("");
            this.totalcost.setText("");
            this.amountpaid.setText ("");
            this.balance.setText("");
            others.setText("");
            search.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_CFActionPerformed

    private void CNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNActionPerformed

    private void amountpaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountpaidActionPerformed
int x;
  try{
        x=Integer.parseInt(this.amountpaid.getText());
        
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "No Values to display","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }// TODO add your handling code here:
    }//GEN-LAST:event_amountpaidActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_balanceActionPerformed

    private void GETBALANCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETBALANCEActionPerformed

        int num1;
        int num2;
        int num3;
        int num4;
        int num5;
        int num6;
        int num7;
        int num8;
        int num10;
        int num11;
        int num12;
        int num13;
        int num14;
        int num15;
        int num16;
        int num17;
        int num18;
        
        
        try{
        num1=Integer.parseInt(this.jeans.getText());
        num2=Integer.parseInt(this.shirt.getText());
        num3=Integer.parseInt(this.tshirt.getText());
        num4=Integer.parseInt(this.sweater.getText());
        num5=Integer.parseInt(this.jacket.getText());
        num6=Integer.parseInt(this.coat.getText());
        num7=Integer.parseInt(this.trouser.getText());
        num18=Integer.parseInt(this.others.getText());
        num8=Integer.parseInt(this.amountpaid.getText());
       num10=Integer.parseInt(this.jeansp.getText());
       num11=Integer.parseInt(this.shirtp.getText());
       num12=Integer.parseInt(this.tshirtp.getText());
       num13=Integer.parseInt(this.sweaterp.getText());
       num14=Integer.parseInt(this.jacketp.getText());
       num15=Integer.parseInt(this.coatp.getText());
       num16=Integer.parseInt(this.trouserp.getText());
       num17=Integer.parseInt(this.txtothers.getText());
        }
        
        catch(Exception e){
        JOptionPane.showMessageDialog(this, "No Value inserted!","ERROR",JOptionPane.ERROR_MESSAGE);
        return;
        }
         
        int balanc = (num8) - ((num1*num10) + (num2*num11) + (num3*num12) + (num4*num13) + (num5*num14) + (num6*num15) + (num7*num16) + (num18*num17));
        this.balance.setText(""+balanc);
      // TODO add your handling code here:
    }//GEN-LAST:event_GETBALANCEActionPerformed

    private void jeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeansActionPerformed

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
Pay_Report();// TODO add your handling code here:
    }//GEN-LAST:event_ReportActionPerformed

    private void sweaterpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sweaterpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sweaterpActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
   try {
          String t =  (String) cboplan.getSelectedItem();
              String sql="select * from pricing where plan like '"+t+"%'";
             rs = st.executeQuery(sql);
          st = (Statement) (java.sql.Statement) conn.prepareStatement (sql);
      
       
      while (rs.next()) {
String js = rs.getString("jeans");
jeansp.setText(js);

      
String sp = rs.getString("collar_shirt");
shirtp.setText(sp);

       
String tp = rs.getString("t_shirt");
tshirtp.setText(tp);
 
        
String srp = rs.getString("pullover");
sweaterp.setText(srp);
        
String jp = rs.getString("jacket");
jacketp.setText(jp);
 
        
String cp = rs.getString("coat");
coatp.setText(cp);

          
String tr = rs.getString("trouser");
trouserp.setText(tr);

String others=rs.getString("others");
txtothers.setText(others);
} 
      
       
        
          
       
        if(!rs.absolute (1)) {
        JOptionPane.showMessageDialog(null, "No results found");
        }
        
    } catch (Exception exp) {
        
         System.out.println (exp);
           JOptionPane.showMessageDialog(null, "Error: " + exp.getMessage());  
    }// TODO add your handling code here:
    }//GEN-LAST:event_displayActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try {
          String t = search.getText();
              String sql="select*from cloth_deposit where Customer_ID like '"+t+"%'";
             rs = st.executeQuery(sql);
          st = (Statement) (java.sql.Statement) conn.prepareStatement (sql);
      
       
      while (rs.next()) {
String js = rs.getString("Jeans");
jeans.setText(js);

      
String sp = rs.getString("Shirt");
shirt.setText(sp);

       
String tp = rs.getString("T_shirt");
tshirt.setText(tp);
 
        
String srp = rs.getString("Sweater");
sweater.setText(srp);
        
String jp = rs.getString("Jacket");
jacket.setText(jp);
 
        
String cp = rs.getString("Coat");
coat.setText(cp);

          
String tr = rs.getString("Trouser");
trouser.setText(tr);
} 
      
       
        
          
       
        if(!rs.absolute (1)) {
        JOptionPane.showMessageDialog(null, "YOU HAVE NOT DEPOSITED ANY LAUNDRY");
        }
        
    } catch (Exception exp) {
        
         System.out.println (exp);
           JOptionPane.showMessageDialog(null, "Error:" + exp.getMessage());  
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
new CustomerNavigation().setVisible(true);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed
public void Pay_Report (){
        
try{
        
String REPORT="C:\\Users\\Kimaiga\\Documents\\NetBeansProjects\\Prestige Drycleaners\\src\\Reciept.jrxml";
JasperReport JASP_REP =JasperCompileManager.compileReport(REPORT);
JasperPrint JASP_PRINT=JasperFillManager.fillReport(JASP_REP,null,conn);
JasperViewer.viewReport(JASP_PRINT);

        }
catch(Exception exp) {System.out.print (exp);}

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        ////////////////////////////////////
        ///////Give the Gui window /////////
        /////// look and feel      /////////
        ////////////////////////////////////
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CALCsub;
    private javax.swing.JButton CF;
    public static javax.swing.JTextField CN;
    private javax.swing.JButton GETBALANCE;
    private javax.swing.JButton Report;
    private javax.swing.JTextField amountpaid;
    private javax.swing.JTextField balance;
    private javax.swing.JComboBox cbomode;
    private javax.swing.JComboBox cboplan;
    private javax.swing.JTextField coat;
    private javax.swing.JTextField coatp;
    private javax.swing.JButton display;
    private javax.swing.JButton getcost;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jacket;
    private javax.swing.JTextField jacketp;
    private javax.swing.JTextField jeans;
    private javax.swing.JTextField jeansp;
    private javax.swing.JTextField others;
    private javax.swing.JTextField search;
    private javax.swing.JTextField shirt;
    private javax.swing.JTextField shirtp;
    private javax.swing.JTextField sweater;
    private javax.swing.JTextField sweaterp;
    private javax.swing.JTextField totalcost;
    private javax.swing.JTextField trouser;
    private javax.swing.JTextField trouserp;
    private javax.swing.JTextField tshirt;
    private javax.swing.JTextField tshirtp;
    private javax.swing.JTextField txtothers;
    // End of variables declaration//GEN-END:variables
}
