/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flush.dry.cleaning.service;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.WindowEvent;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.event.ChangeListener;

import javax.swing.JOptionPane;

/**
 *
 * @author Kimaiga
 */
public class Pricing extends javax.swing.JFrame {
        Connection conn= null;
        PasswordEncryption ps;
        String url = "jdbc:mysql://localhost/";
        String dbName = "flush_drycleaners";
        String driver ="com.mysql.jdbc.Driver";
        String userName = "root";
        String password = "";
        Statement st;
        ResultSet rs;
    SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
    private String UI;
    
    
     public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    


    /**
     * Creates new form Laundry_costs
     */
    public Pricing() {

        
        initComponents();
         setLocationRelativeTo(null);
        this.setResizable(false);
               
        
         try{
	       Class.forName(driver);

             conn = (com.mysql.jdbc.Connection) DriverManager.getConnection(url+dbName,userName,password);

              st = (com.mysql.jdbc.Statement) conn.createStatement();

          //   this.setTitle("Users Account");

	      }


	            catch(Exception exp)
                    {
	              JOptionPane.showMessageDialog(null, "Cannot connect to the database,check network settings.","ERROR",JOptionPane.ERROR_MESSAGE);
	            }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtjeans = new javax.swing.JTextField();
        shrt = new javax.swing.JTextField();
        tt = new javax.swing.JTextField();
        sr = new javax.swing.JTextField();
        tr = new javax.swing.JTextField();
        ct = new javax.swing.JTextField();
        jt = new javax.swing.JTextField();
        Submitcosts = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cboplan = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        srch = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtothers = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LAUNDRY PRICING");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Laundry Pricing");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Jeans");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Shirt");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Tshirt");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Sweater");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Trouser");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Coat");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Jacket");

        Submitcosts.setText("Save");
        Submitcosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitcostsActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Price ID");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Plan");

        cboplan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--SELECT A PRICE PLAN--", "Normal" }));
        cboplan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboplanActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setText("Plan");

        srch.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        srch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal price" }));

        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear fields");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Search Area");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel13.setText("Others");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(cboplan, 0, 207, Short.MAX_VALUE)
                                            .addComponent(pid))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel10)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtjeans, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(shrt)
                                    .addComponent(tt)
                                    .addComponent(sr)
                                    .addComponent(tr)
                                    .addComponent(ct)
                                    .addComponent(jt)
                                    .addComponent(txtothers))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(Submitcosts)
                                .addGap(50, 50, 50)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboplan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtjeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtothers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(srch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submitcosts)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 new AdministratorNaviagtion().setVisible(true);
 dispose();
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SubmitcostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitcostsActionPerformed
 String pid1 = pid.getText();
         try {
             Integer.parseInt (pid1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "EMPTY FIELDS", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String ssn = (String) cboplan.getSelectedItem();
          
          String js1 = txtjeans.getText();
         try {
             Integer.parseInt (js1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at jeans", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String st1 = shrt.getText();
         try {
             Integer.parseInt (st1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at shirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String tt1 = tt.getText();
         try {
             Integer.parseInt (tt1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at tshirt", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String sr1 = sr.getText();
         try {
             Integer.parseInt (sr1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at sweater", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String jt1 = jt.getText();
         try {
             Integer.parseInt (jt1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at jacket", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String ct1 = ct.getText();
         try {
             Integer.parseInt (ct1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at coat", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
          String tr1 = tr.getText();
         try {
             Integer.parseInt (tr1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at trouser", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
             
         }
         
String otherClothes=txtothers.getText();
            try {
             Integer.parseInt (tr1);
         } catch (NumberFormatException nfe) {
              JOptionPane.showMessageDialog(this, "Incorrect input at others", "ERROR", JOptionPane.ERROR_MESSAGE);
             
             return;
         }
   try{

            String sql = "INSERT INTO pricing (price_id, plan, jeans, collar_shirt, t_shirt, pullover, jacket, coat, trouser,others) VALUES('"+pid1+"','"+ssn+"', '"+js1+"', '"+st1+"', '"+tt1+"','"+sr1+"', '"+jt1+"', '"+ct1+"', '"+tr1+"','"+otherClothes+"')";
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Details succesfully saved!", "Confirmatory Message", JOptionPane.PLAIN_MESSAGE);

            this.pid.setText("");
            this.txtjeans.setText("");
            this.shrt.setText("");
            this.tt.setText("");
            this.sr.setText("");
             this.jt.setText("");
            this.ct.setText("");
            this.tr.setText("");
            txtothers.setText("");
// TODO add your handling code here:
     
        }catch (SQLException err){
            JOptionPane.showMessageDialog(this, err.getMessage());
            
        }
        // TODO add your handling code here:
      // TODO add your handling code here:
    }//GEN-LAST:event_SubmitcostsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  try {
          String t =  (String) srch.getSelectedItem();
              String sql="select*from pricing where plan like '"+t+"%'";
             rs = st.executeQuery(sql);
          st = (Statement) (java.sql.Statement) conn.prepareStatement (sql);
      
       
      while (rs.next()) {
          String pd = rs.getString("price_id");
pid.setText(pd);


          
String jsp = rs.getString("jeans");
txtjeans.setText(jsp);

      
String sp = rs.getString("collar_shirt");
shrt.setText(sp);

       
String tp = rs.getString("t_shirt");
tt.setText(tp);
 
        
String srp = rs.getString("pullover");
sr.setText(srp);
        
String jp = rs.getString("jacket");
jt.setText(jp);
 
        
String cp = rs.getString("coat");
ct.setText(cp);

          
String trp = rs.getString("trouser");
tr.setText(trp);

String otherClothes=rs.getString("others");
txtothers.setText(otherClothes);
} 

        if(!rs.absolute (1)) {
        JOptionPane.showMessageDialog(null, "No results found");
        }
        
    } catch (Exception exp) {
        
         System.out.println (exp);
           JOptionPane.showMessageDialog(null, "Error: " + exp.getMessage());  
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
int test = JOptionPane.showConfirmDialog(null, "Update this record?", "Update", JOptionPane.OK_CANCEL_OPTION);
            if (test == 0) {
 String pd = pid.getText ();       
String jsp = txtjeans.getText();     
String sp = shrt.getText();      
String tp = tt.getText();       
String srp = sr.getText();
String jp = jt.getText();
String cp = ct.getText();
String trp = tr.getText();
String search = (String) srch.getSelectedItem();

       
        
       
        try{
            st = conn.createStatement();
            String sql = "UPDATE pricing SET plan = '"+search+"', price_id = '"+pd+"' ,jeans = '"+jsp+"', collar_shirt = '"+sp+"', t_shirt = '"+tp+"', pullover = '"+srp+"', jacket = '"+jp+"', coat = '"+cp+"', trouser = '"+trp+"' WHERE plan ='"+search+"'";
            int Keta = st.executeUpdate(sql);
            
                JOptionPane.showMessageDialog(Pricing.this, "Record ID '"+search+"' Updated");
            }
            catch (SQLException err) {
                   System.out.println(err.getMessage() );
            }
        
            }else{
                //User presses cancel  
            }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Pricing lc = new Pricing ();
 lc.setVisible(true); 
 dispose ();// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cboplanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboplanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboplanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        ////////////////////////////////////
        ///////Give the Gui window /////////
        /////// look and feel      /////////
        ////////////////////////////////////
        try {
                      UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

                    } catch (Exception e) {
                      System.err.println("Look and feel not set.");
                    }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pricing().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submitcosts;
    private javax.swing.JComboBox cboplan;
    private javax.swing.JTextField ct;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jt;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField shrt;
    private javax.swing.JTextField sr;
    private javax.swing.JComboBox srch;
    private javax.swing.JTextField tr;
    private javax.swing.JTextField tt;
    private javax.swing.JTextField txtjeans;
    private javax.swing.JTextField txtothers;
    // End of variables declaration//GEN-END:variables
}
