/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package flush.dry.cleaning.service;

import com.jtattoo.plaf.texture.TextureLookAndFeel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Kimaiga
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    public SplashScreen() {
        
        final Timer  timer;

        ActionListener updateProBar = new ActionListener() {
      public void actionPerformed(ActionEvent actionEvent) {
        int val =  jProgressBar1.getValue();

        if (val <= 100) {

       jProgressBar1.setValue(++val);
        }

         if (val ==1){
             x.setText("Initializing modules");
             
        }
        
        if (val == 20){
             x.setText("Loading modules ");
             
        }
           if (val == 40){
            x.setText("");
             
        }  
             if (val == 60){
            x.setText("");
             
        }
           
         if (val == 80){
            x.setText("Done Loading Modules| Loaded succesfully");     
        }
        if (val == 100){
             new SelectAccessLevel ().setVisible(true);
             setVisible(false);
        }


      }

    };

timer = new Timer(100, updateProBar);
    timer.start();



        initComponents();
this.setResizable(false);
this.setTitle("WELCOME");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        x = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(10, 332, 670, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Kimaiga\\Documents\\NetBeansProjects\\Prestige Drycleaners\\Laundry logo.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 670, 310);
        getContentPane().add(x);
        x.setBounds(290, 350, 330, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-701)/2, (screenSize.height-414)/2, 701, 414);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
        
        ////////////////////////////////////
        ///////Give the Gui window /////////
        /////// look and feel      /////////
        ////////////////////////////////////
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_regis_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_regis_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_regis_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_regis_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 
                new SplashScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel x;
    // End of variables declaration                   
}
